### ISSUE TITLE
Real time

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#11]
Hi Guys
Is there a way that we can send data to the portals in real time?
If so what will it involve or is there a simple resolution?
Best
Viv

**Comment by therealmyth** [comment]
I know Zoopla has a real time feed, and Doug asked for a quote on implementing this (see issue #6 ). It would take around 2-3 days to implement and test, and Zoopla requires 7 days of error free feed before they approve it to go live.

**Comment by therealmyth** [comment]
Closing: Duplicate #18
