### ISSUE TITLE
Uploading to sites

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#12]
Another question.
Is there a way that we can upload to one portal (other than our own) and not another?
Thanks
V

**Comment by therealmyth** [comment]
At the moment we can enable/disable portals site wide, but not on a property basis, this would require some changes to the admin interface and the  exporting script. We could probably do this at the same time than the real time feed if you plan to go ahead with this. I would think 2-3 hours should be enough to implement.

**Comment by Vivharris** [comment]
Perhaps you can let me know if the real time feed would now form part of our monthly package.
Thanks
V

T   020 7435 3344
M 07976 737172
E   vivharris@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image008.png@01D25617.DC914470]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Hi Viv, 

Your support contract include 24h per quarter, and there's 5 gone already. The real time feed would take from 16 to 24 hours to implement, so it may deplete you hours and even go over with this one job. So I would probably do it as a separate job if I was you. 

regards, 

f
