### ISSUE TITLE
£ signs not showing in text

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#14]
Last one for today.
It seems that £ signs are not showing on either Zoopla or OntheMarket.
As we are required to have details of monthly rent amounts and fees it would be good if this could be corrected asap.
It looks a bit naff currently.
Thanks
V

**Comment by therealmyth** [comment]
Will investigate and fix, I've been contacted by Zoopla this AM with more debugging info on this. Will come back to you when done

**Comment by therealmyth** [comment]
I had a look today, and this seems to happen during the encoding of the file. This is the 2nd encoding function already, and both had their issues. I have tested some other way without any luck so far, I will continue and update you.

**Comment by therealmyth** [comment]
This will be fixed by the real time feed, I cannot find an encoding function that can handle all the special characters properly.  When the pound signs works, other character are missing, and vise versa. Since the text now uses GBP instead of the symbol, I'm closing this one.
