### ISSUE TITLE
Bullet poits on upload to Zoopla

### ISSUE THREAD

**Issue by dougmheathgate** [ActivateMedia/heathgate#15]
It would appear that the bullet points for properties are only sending 3 (out of a possible 10) it seems to be that the bullet points are sent as "feature 1", "feature 2" etc and as I stated three are only 3 which are randomly selected. Can we resolve this so that up to 10 are sent please?

**Comment by dougmheathgate** [comment]
I have spoken to OnThe Market too just now and we have the exact same issue so it IS the data we send

**Comment by therealmyth** [comment]
Will check at the same time than the pound sign issue.

**Comment by therealmyth** [comment]
I think that when we initially develop the site and the export script, Rightmove didn't allow for more than 3 features. I updated the export script now and the feed should now include up to 10 features.
