### ISSUE TITLE
Testimonials on the website 

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#16]
Please can someone have a look there are the top 2 testimonials that appear differently than the remainder. I have tried to work out what to do but cannot seem to get it right,
We used to be able to amend this page ourselves and wondered if this function has been removed.
It looks somewhat untidy at present so would be grateful for a rapid response.
Thanks Viv

**Comment by therealmyth** [comment]
This has been fixed, there was a few other issues with a some of the other testimonials which has been fixed as well.

**Comment by Vivharris** [comment]
Thank you
V

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D277EB.3445B850]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32
