### ISSUE TITLE
Web Optimisation

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#17]
Good morning,
Hope you are well.
I was wondering whether there is a way to get better web optimisation and whether we need to change any wording for to create more key words etc.  If there is a way to do this please let me know or you have any ideas in this regard I would be grateful to hear them.
We are looking to see how we can get further up the Google ratings.
Thanks
Viv

**Comment by gregrice** [comment]
HI Viv,

These days it is pretty much about content more than anything else. I don't think potential clients search for agents- but more for types of properties in certain locations. The other factor is inbound links from relevant sites.

The single biggest improvement in my mind would be to put some really targeted copy on the top part your home page. probably under the large photo and above the each.

Something like:
Established in 1990, Heathgate is one North London's most experienced Estate agents. We specialise in working with the best properties in Hampstead, Belsize Park, Highgate and Hamspstead Garden Suburb. 

Fred- other ideas?

**Comment by therealmyth** [comment]
I guess that sums it up, from my limited understanding of the search engines, the more link pointing to your site, the more weight you get in the search results. The targeted copy usually makes it, as other site will usually point to you as a reference. But my knowledge is very limited on this issue.
