### ISSUE TITLE
Maximising HG Website 

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#19]
Hi 
Hope all good with you.
I have just read the article below and wonder what we can do (if anything) to implement any of the points raised.
Please have a read and see what you think.
The author is a former head of SEO at Zoopla, Mail Online and Yell. He is founder of Blue Array, an SEO agency that specialises in large-scale SEO
Thanks
Viv x

**Opinion: Why do agents neglect their own websites in favour of the portals?**

Ever since they launched, the influence of Rightmove and Zoopla on the public has been undeniable.

Indeed, in 2014, eight out of ten home owners said they would bypass estate agents altogether if they could list their homes directly on both sites.

Agents have mixed feelings about the portals, given that it is their own inventory that powers them.

However, have estate agents developed an over-dependence on the likes of Rightmove and Zoopla at the expense of optimising their own websites?

For over a decade now Google has prioritised small local businesses within its search results underneath or alongside map results.

Since the Venice update in 2012, Google has understood generic queries such as “estate agents” to be deserving of localised results based on the user location.

The Pigeon update then came along in July 2014 to see more traditional SEO signals (primarily links) give more sensible weighting to the local results as opposed to distance from centre of the user’s location.

A further update was implemented in August 2015 which saw Google’s “Local Pack” change from showing seven results at a time to just three – suggesting to the user that the top results were the most trustworthy.

However, this required businesses to more aggressively optimise their local landing pages in order to stand a chance of being featured.

Nevertheless, Google is giving local estate agents a huge advantage over aggregate sites and they could be wasting this opportunity by not investing in their own websites and improving their SEO presence.

What’s more, it has been suggested that, despite Zoopla and Rightmove receiving a lion’s share of traffic, users aren’t going to these sites directly and are instead searching terms such as “houses for sale in Exeter” or “estate agents in Exeter” to at least get whole of market coverage.

Again, this is giving local estate agents a great advantage.

My own firm, Blue Array, looked at a random sample of over 400 estate agency websites to assess their basic SEO strategies to give an indication on how the industry is performing as a whole.

Of the estate agents’ websites we examined, 91/100 had optimised their sites for mobile, which is excellent, but many had made some elementary mistakes.

For example, 34% of the websites we inspected had duplicate versions of their home pages. Whilst there is no penalty for having duplicate content on your website, unless it appears to be deliberately trying to manipulate search engine results, it does potentially split the link power of inbound efforts and internal links.

In addition to duplicate content, we found that 35% of estate agent websites had unoptimised meta descriptions which could result in a poor click-through rate.

Essentially, a meta description is a brief summary of your content that appears on Google to entice a user to click through to your website and it’s a great place to highlight your value proposition.

However, all is not lost and there are some simple steps that estate agents can do to ensure they’re not so wholly reliant on portals or aggregator sites and instead drive organic traffic to their own websites.

Optimise your ‘My Google Business’ page
Google determines a business’s local ranking through using the information provided on the company’s ‘Google My Business Page’.

It’s vital that a business has a Google+ Business page and tells it as much about the business as it can to ensure visibility within local SERPS.

First and foremost the most vital information that needs to be correct is a business’s NAP details (Name, Address and Phone Number), as these details are one of the key factors that impact rank listings.

Google uses this information to help determine the business’s proximity to the user and uses citation analysis (the presence of this NAP data) on trusted third party sites to validify the business.

Localise landing pages
Another way an estate agent can improve their localised search rankings is through optimising all of their landing pages with relevant, geographical keywords.

Companies should first of all be including their NAP details on all their landing pages to boost positionings.

These companies should not just be optimising their landing pages with NAP details, but they also need to be localising their content.

This includes titles, labelling of pictures and sharing of local goings on in the area they do business.

For example, an estate agent in Reading should be ensuring that they are incorporating local keyword elements into both new and existing content.

Businesses need to research their audiences and build their content around this. They can do this by writing content around particular subjects relevant to their area, promoting events nearby or writing about local suppliers.

Stay mobile
Whilst many of the estate agent websites we examined had optimised their websites for mobiles, it’s important they realise that these localised updates are continually being created and changed to coincide with mobile devices.

Mobile devices automatically use localised results (all searches on Google Mobile are deemed of local intent) and, with the increased use of mobile search, Google will keep the updates coming in order to optimise its search engine to provide relevant content.

Businesses need to ensure they have a mobile-friendly website and an SEO strategy that suits both their desktop website and mobile version. A key here is to keep up to date with how users are utilising mobile search and the keywords they’re using to find estate agents’ websites.

Whilst portal platforms such as Zoopla and Rightmove and aggregators such as Nestoria have revolutionised the property industry, estate agents should not be overlooking their own websites.

Conclusion

With Google giving priority to smaller businesses, now is the time to look at your own website to see how you might be able to increase its Google ranking.

Making just a few changes could increase organic traffic to your website and generate sales leads without the dependency on property aggregators’ and portals’ SEO efforts.

**Comment by therealmyth** [comment]
Closing, let's make issue #17 the SEO ideas ticket.
