### ISSUE TITLE
Properties rejected by Zoopla

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/heathgate#2]
19 Harmood Grove and Flat 89 Heathcroft rejected for lack of second half of postcode. The full postcode appears to be there in the CMS.

**Comment by adrian-activate** [comment]
Email sent to Doug

Hi Doug,

I had a look at the properties you mentioned and could not see an obvious difference between them and properties that are successfully showing on Zoopla. So Andrea will investigate further into why these properties are not uploading today. It would be helpful if we had access to the error reports you are receiving from Zoopla. If these are through and admin panel could you give us access?

Many Thanks

Adrian

**Comment by adrian-activate** [comment]
@andreafalzetti did you look at this?

**Comment by adrian-activate** [comment]
@andreafalzetti 

Dear Activate Media,

A mutual client of ours Heathgate, 105 Heath Street, London NW3 6SS (heathgate ID:  3785) has contacted us in regards to the following properties being rejected on Zoopla:

invalid incode (16)  
Listing ID  Source listing ID   Source branch ID    Postal code Type    Price
40787120    3785_11085  3785    W9  rent    £595
39183554    3785_7511   3785    NW8 rent    £1,100
39183553    3785_7499   3785    NW8 rent    £1,100
40243974    3785_9728   3785    NW3 rent    £525
40190089    3785_9609   3785    NW11    sale    £765,000
40960825    3785_11478  3785    NW3 rent    £15,000
40046502    3785_9322   3785    NW8 rent    £1,100
39487963    3785_7849   3785    NW3 rent    £600
40968440    3785_9481   3785    NW8 rent    £1,500
40692395    3785_10709  3785    NW1 rent    £630
40046503    3785_9337   3785    NW11    rent    £1,950
40853504    3785_11195  3785    SW6 rent    £2,750
40692394    3785_10708  3785    NW1 rent    £480
40787122    3785_10957  3785    NW1 sale    £550,000
39183552    3785_7487   3785    NW8 rent    £1,100
40116385    3785_9493   3785    NW8 rent    £1,100

The above properties are missing the 2nd part of the postcode as per below example:

'AGENT_REF' => '3785_11085'
'POSTCODE1' => 'W9',
'PRICE' => '595',

The POSTCODE2 field is missing

Also 6 properties have been rejected below:

status: (6)  
Listing ID  Source listing ID   Source branch ID    Postal code Type    Price
37111214    3785_5070   3785    NW11    sale    £3,500,000
38162447    3785_6358   3785    NW3 1TL rent    £450
34499654    3785_2824   3785    NW3 6SS sale    £1,000,000
37827139    3785_6043   3785    NW3 5TN rent    £550
39599325    3785_7974   3785    N2 0DE  rent    £925
33709998    3785_2088   3785    NW3 6SZ sale    £1,100,000

Example Property:

'AGENT_REF' => '3785_5070'
'STATUS_ID' => '6',

STATUS_ID of 6 does not exists within the RMV3 feed specification.

Can you please correct the above making sure the full postcode is coming through to Zoopla and that the agent is aware of how to enter the full postcode on their system as well as the Status errors outlined above?

If you require any further information or if I can be of further assistance please do not hesitate to contact me.

Thank you

Kind Regards

Alexi Dimas
Technical Support Executive, ZPG

T - 020 3544 1000
F - 0207 620 4770
E - members@zpg.co.uk

**Comment by andreafalzetti** [comment]
**Update**

I have investigated a part of the script and it seems that:
1. the full address in the CMS is stored as a String and the postcode is extracted using a regular expression. I tried to isolate that portion of code, to see if it works well, running tests on the addresses where the second part of the postcode was missing and I can confirm it worked well on. I need to understand the moment when the second half of the postcode gets lost or what happens to it. The archive files are deleted every time and Zoopla deletes them as well so I cannot investigate the submission right now. I will try to leave a copy on our system at the next cycle.
2. status ID 6 means "Sold" in the script. Some agents use different codes, I need to double check the Zoopla documentation to verify what set of codes they use.

**Comment by andreafalzetti** [comment]
I've updated the script replacing the previous postcode extraction part. I will run the script to see if the rejected properties get approved.

**Comment by adrian-activate** [comment]
Good afternoon,
Just checked the back end of Zoopla and as you can see I think the problem is sorted. The 4 properties showing as rejected were errors here (which have now been rectified).

Obviously we will keep a check on things but I would like to thank you for getting things resolved.

Have a good weekend,

Kind regards

Doug
