### ISSUE TITLE
A few more issues to resolve 

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#21]
Hi Greg and Fred
Hope you are both well.
1 On the back end. When you type in the accommodation such as 2 bedrooms etc (on the right hand side of the screen) it does not appear as it is written and changed capital letters to lower case which looks really unprofessional on the site. Please can this be corrected. It also moves things into alphabetical order and it would be better if this could also be stopped.
2 Sometimes when you mark a property as detached it comes up as terraced on the other websites. This must be some coding issue and I would be grateful if you could look at it. Middleway at £2,250,000 is an example.
3 When you log in to wpcasa often the password is not remembered and if it is it asks you to re-type it, can this be resolved.
4 Are we now running on real time updates to Zoopla?
Thanks in advance for all your help.
Viv x

**Comment by therealmyth** [comment]
Duplicate: #22
