### ISSUE TITLE
Various issues  Please see attached

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#22]
Hi Greg and Fred
Hope you are both well.
1 On the back end. When you type in the accommodation such as 2 bedrooms etc (on the right hand side of the screen) it does not appear as it is written and changed capital letters to lower case which looks really unprofessional on the site. Please can this be corrected. It also moves things into alphabetical order and it would be better if this could also be stopped.
2 Sometimes when you mark a property as detached it comes up as terraced on the other websites. This must be some coding issue and I would be grateful if you could look at it. Middleway at £2,250,000 is an example.
3 When you log in to wpcasa often the password is not remembered and if it is it asks you to re-type it, can this be resolved.
4 Are we now running on real time updates to Zoopla?
Thanks in advance for all your help.
Viv x

**Comment by fredturmel** [comment]
Hi Viv, 

1. I can't seem to replicate the issue you are describing, could you be more specific as to where you are entering the accommodation (page and field) ?

2. This is usually due to a property description not matching the presets in the export script. the available values are (without the quotes): "Ambassadorial style", "Bungalow", "Brand new penthouse", "Chalet Bungalow", "Conversion", "Converted Flat", "Detached", "Detached House", "Development Opportunity", "Duplex", "Duplex Flat", "End of Terrace", "Flat", "House", "Linked", "Low Built Detached", "Low Built Semi-detached", "Maisonette", "Mansion", "Mansion Flat", "Mews House", "Penthouse", "Purpose Built Duplex Flat", "Purpose Built Flat", "Semi Detached", "Semi-detached", "Shop and Upper Parts", "Terraced", "Town House", "Triplex".  I have changed it to being case insensitive but it still need to match one of the above to be correctly mapped.

3. The stored credentials are usually handled by your browser and not the website, so there's no real solution on the website to fix that. 

4. I am still having error on the test instance with the live feed, I am working to correct it and will advise when ready to go.

**Comment by fredturmel** [comment]
Hi Viv, 

I have requested a certificate to Zoopla for when we are ready to switch the live feed on. They should contact you shortly and provided me with a token they will ask to confirm you are aware of the request, it is : DBNO-TNYK-MUMG

**Comment by Vivharris** [comment]
Hi Fred,
We seem to have another problem with the website. When you ask to create PDF details from the site it says it can’t find the page (with error code 500).
Please can you investigate and fix this asap.
Thanks
Viv

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D312A8.A6E3D0B0]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Hi Viv, 

Any particular property? I can't seem to replicate the issue on my side.

Fred

**Comment by Vivharris** [comment]
Westfield – just added.

Vivienne Harris

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D312AC.455D8CB0]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
The was a memory limit issue, I changed the server settings now and it generates fine. 

Fred

**Comment by Vivharris** [comment]
Hi Fred
Did you publish the Lyndhurst Road flats that were in drafts?
They seem to have shown on our webpage although no-one here added them.
I have moved them to trash as they should not have been live.
Best
Viv

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D312CF.B8AF68F0]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Hi Viv,

I did had to go through and save each properties to have them propagate 
to the live real-time feed, we are going live with it today or Monday, 
that might have happened then by mistake, sorry about that. Could you 
check if I would have published some more the same way?

Fred

------ Original Message ------

**Comment by Vivharris** [comment]
Have been through them. All ok now.

V

Office: 020 7435 3344
Mobile: 07976 737 172

HEATHGATE
105 Heath Street, Hampstead, London, NW3 6SS
Fax: 020 7433 3344   Website: www.heathgate.com<http://www.heathgate.com>

On 11 Aug 2017, at 19:23, therealmyth <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Viv,

I did had to go through and save each properties to have them propagate
to the live real-time feed, we are going live with it today or Monday,
that might have happened then by mistake, sorry about that. Could you
check if I would have published some more the same way?

Fred

------ Original Message ------
