### ISSUE TITLE
Front and back end areas for amendment please 

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#23]
Hi Fred,
This are the boxes back end and front end of web. Can we have them arranged non alphabetically, just in the order in which they are typed please?
![back of web](https://cloud.githubusercontent.com/assets/23172418/26397813/6f0344ec-406f-11e7-8592-ce7c9c543e8c.JPG)
and
![front of web](https://cloud.githubusercontent.com/assets/23172418/26397845/857b6ef2-406f-11e7-8ef4-d1204bdc6779.JPG)
Thanks
Viv

**Comment by therealmyth** [comment]
This now shows in the order they were added
