### ISSUE TITLE
Losing properties from website

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#25]
Hi All,
Not sure if you can shed any light but we appear to have a number of letting properties that have disappeared from our website. This is a problem as we rely on the properties remaining live until we remove them, I have clients complaining that their properties cannot be seen, we are losing loads of business because we are not getting the enquiries and my administrator is having a nervous breakdown at having to put them all back on. Can you please investigate this as a matter of urgency. I can guarantee that no one from here has removed them and that they were originally on the site. Haverstock Hill at £325 per week I loaded myself last Saturday and today it was showing without a price and for sale???? URGENT ATTENTION PLEASE.
Thanks
Viv

**Comment by andreafalzetti** [comment]
Hi @therealmyth, have you had the chance to look into this?

**Comment by therealmyth** [comment]
Hi @Vivharris 

Is this still happening? or was it a one off.

**Comment by Vivharris** [comment]
Seems ok currently

Vivienne Harris

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D2FAF2.7E63B920]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Ok closing for now, 

Please raise another ticket if that was to happen again, we can investigate the logins/server activity then. 

Fred
