### ISSUE TITLE
Web Chat/Online Valuation Tool

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#26]
Hi All,
Hope you are well.
I am looking at installing a web chat facility and an online Valuation tool onto the home page of the website. Is this possible and what do you need from me in order to make this happen.
Thanks
Viv

**Comment by therealmyth** [comment]
Hi Viv, 

I know you are happy with the chat tool Andrea pointed you to, so I will have a look to install it this weekend. I will let you know if I need any graphics from you but I should be fine with what we have so far to style the plugin. 

As for the valuation tool, do you want a form to request a valuation? or are you thinking about something more specific? 

f

**Comment by Vivharris** [comment]
Yes will be in touch on Monday re this.
Thanks and have a great weekend.
Viv

Office: 020 7435 3344
Mobile: 07976 737 172

HEATHGATE
105 Heath Street, Hampstead, London, NW3 6SS
Fax: 020 7433 3344   Website: www.heathgate.com<http://www.heathgate.com>

On 23 Jun 2017, at 18:51, therealmyth <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Viv,

I know you are happy with the chat tool Andrea pointed you to, so I will have a look to install it this weekend. I will let you know if I need any graphics from you but I should be fine with what we have so far to style the plugin.

As for the valuation tool, do you want a form to request a valuation? or are you thinking about something more specific?

f

**Comment by therealmyth** [comment]
Hi Viv, just sent you an email with a screenshot for the web chat, please let me have you thought  when you can. 

f

**Comment by therealmyth** [comment]
Hi Viv, 

I created your account, you should receive an activation link to your email, please let me know when you had a chance to do the activation.

f

**Comment by Vivharris** [comment]
Is that click desk?

Vivienne Harris

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D2EEA0.696DB060]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Yes


------ Original Message ------

**Comment by Vivharris** [comment]
1.        
2.        <script type='text/javascript'>
3.        var _glc =_glc || []; _glc.push('all_ag9zfmNsaWNrZGVza2NoYXRyEgsSBXVzZXJzGICAoMWM4dIJDA');
4.        var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' :
5.        'http://my.clickdesk.com/clickdesk-ui/browser/');
6.        var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
7.        var glcspt = document.createElement('script'); glcspt.type = 'text/javascript';
8.        glcspt.async = true; glcspt.src = glcpath + 'livechat-new.js';
9.        var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(glcspt, s);
10.     </script>
11.     
This is what was sent through

V

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D2EEA1.26201DB0]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Thanks, 

The account is now completed, I also added the code to he site so the chat/contact window should now be showing up. There are 2 admin section: Admin Dashboard and Agent Portal. The admin dashboard lets you define the settings for the chat window, and the Agent Portal is where you can handle the live chats. 

The Admin dashboard URL: https://my.clickdesk.com/
The Agent portal URL: https://5430525655777280.clickdesk.com/agent/login

Username is viv@heathgate.co.uk, will send the password in a seperate email.

The free account allows for only one agent, so I gave it the generic name of Heathgate Properties, that will allow anyone in your office you give the credential to to handle the chat requests. The agent portal will ask you to add an extension to your browser in order to work, just follow the instructions. 

In the admin dashboard, you can customize a variety of settings like the online and offline Bar text, images etc... Let me know if you are unsure on how to set somethings and I'll be more than happy to help. 

Let me know if anything, and will wait to hear from you on the valuation tool.

Fred

**Comment by Vivharris** [comment]
Thank you Fred. Much appreciated.
Will revert re the valuation tool.
V

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D2EEA3.4D389740]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by gregrice** [comment]
@Vivharris- I am going to close this for now- please start a new issue when you are ready to go with the Valuation tool.

**Comment by Vivharris** [comment]
Have asked Steve from Nethouseprices.com to contact Fred and given him Fred's e-mail. Do I need to do anything else?
