### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#28]
Hi Guys
Urgent please. The front end of our website is not displaying properly, so no pictures for most of the properties.
Have also just added a new property that is not showing on the front.
Please can you investigate -  urgent urgent!
Thanks
Viv

**Comment by gregrice** [comment]
@andreafalzetti- can you have a quick look- they are going to put up a screen grab for us

**Comment by andreafalzetti** [comment]
Hi @Vivharris, 

Both Greg and I can see the property you are referring to, from 2 different computers. 

I don't see any technical issue on the site. Can you try again and ideally from a different computer or refreshing the browser cache?

Thanks,
Andrea

![screen shot 2017-06-28 at 13 17 10](https://user-images.githubusercontent.com/2318450/27636648-5ef8b81a-5c04-11e7-82bf-3da131c6a78d.jpg)

**Comment by gregrice** [comment]
I have checked it on two different computers- both high res- both on Chrome- all fine

**Comment by Vivharris** [comment]
Still not showing here. Have removed history.

**Comment by gregrice** [comment]
not history- go to "more tools" then select clear browsing data. I have checked it on a couple different browsers now and is how it should be

**Comment by Vivharris** [comment]
Thanks. All back on. Sorry to drive you mad.
