### ISSUE TITLE
Front of web page 

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#29]
Please see attached what we see on screen
![web 1](https://user-images.githubusercontent.com/23172418/27635654-c6c3c6ba-5bff-11e7-83f7-d7d28771fd9e.JPG)
![web 2](https://user-images.githubusercontent.com/23172418/27635657-ccdb8196-5bff-11e7-9378-07536758601b.JPG)

**Comment by andreafalzetti** [comment]
Duplicated of #28
