### ISSUE TITLE
Web Chat

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#30]
I keep getting e-mails saying I've exceeded the limit. See below. it may be nothing but thought you should see it. We don't have heathgate,dev so unsure what this is all about.
Thanks Viv 

Dear Heathgate Properties,

We see that you have already using ClickDesk live chat script on heathgate.com. 

Also we noticed that you are trying to use ClickDesk live chat script on http://heathgate.dev but your plan does not support to use more than 1 website.

If you wanted to use on http://heathgate.dev please upgrade your account or change your settings by accessing "Departments & Code - > Websites tab" page in your ClickDesk Admin Dashboard. 

Please feel free to write us if you have any queries.

**Comment by therealmyth** [comment]
Hi Viv, 

Sorry about that, the code was still running on my development branch. I removed it now and you should stop receiving these emails.

Fred

**Comment by Vivharris** [comment]
No worries. Thanks for letting me know.
