### ISSUE TITLE
Valuation tool for the website

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#31]
Morning Fred and Greg,
Please see below the codes you will need in order to embed the tool into our website.

Many thanks for your email. Here is the code for the Heathgate AVM to have embedded in your website to activate:

<iframe style="width: 100%; height: 1200px; border: none;" scrolling="yes" src="https://nethouseprices.com/widget/sold-prices/?id=A52332E3B025D1"></iframe>

<iframe style="width: 100%; height: 1200px; border: none;" scrolling="yes" src="https://nethouseprices.com/widget/sold-prices/?id=A52332E3B025D1&type=sale"></iframe>

<iframe style="width: 100%; height: 1200px; border: none;" scrolling="yes" src="https://nethouseprices.com/widget/sold-prices/?id=A52332E3B025D1&type=rent"></iframe>

Any queries please let me know.
Thanks
Viv

**Comment by therealmyth** [comment]
thanks Viv, will do later today

Fred

**Comment by therealmyth** [comment]
Just adding the below for reference, Viv have you had any thoughts on the position of the button?:


Hi Viv, 

There's no pretty way to stack the 2 tools with the chat free version, as I can't change the css/styles generated. I can build a similar button on the left hand side, or at the top right... let me know what you think

Fred

------ Original Message ------
From: "Frederic Turmel" <frederic.turmel@gmail.com>
To: "Vivienne Harris" <Viv@heathgate.co.uk>
Cc: "Greg Rice" <greg@activate.co.uk>
Sent: 2017-07-03 1:36:45 PM
Subject: Re[4]: Valuation tool

I have little control on the behavior of the chat button, it's entirely controlled by the code they provides (creates the button and place it based on the configuration, and manage the windows etc...).

Let me see if I can find a way to stack both tools on the bottom right, else we may have to find another placement for the valuation button.

Fred

------ Original Message ------
From: "Vivienne Harris" <Viv@heathgate.co.uk>
To: "Frederic Turmel" <frederic.turmel@gmail.com>
Cc: "Greg Rice" <greg@activate.co.uk>
Sent: 2017-07-03 1:29:06 PM
Subject: RE: Re[2]: Valuation tool

I think it needs to be on the home page.
Maybe above the chat window with a button that says instant valuation tool or maybe make the online chat  a button too and we can have one above the other?
 
From: Frederic Turmel [mailto:frederic.turmel@googlemail.com] 
Sent: 03 July 2017 18:23
To: Vivienne Harris
Cc: Greg Rice
Subject: Re[2]: Valuation tool
 
We can do something like the "Questions?" section on the site, ie Get your free instant valuation. With a button loading the tool in a lightbox. We can load the main tool from the home page, or the Sales or Rental specific tool based on the listing they are looking at. 
 
Fred
 
------ Original Message ------
From: "Vivienne Harris" <Viv@heathgate.co.uk>
To: "Frederic Turmel" <frederic.turmel@gmail.com>
Cc: "Greg Rice" <greg@activate.co.uk>
Sent: 2017-07-03 1:16:15 PM
Subject: RE: Valuation tool
 
How would it look of we matched it up on the bottom left hand side of the home page? Or should there be a button that just says click for instant valuation/valuation tool?

**Comment by therealmyth** [comment]
For reference, pls ignore: 

Button for instant valuation – we think it should be symmetrical with the online chat button to the bottom left of the screen – can we make it look similar so that when you visit the home page it keeps it clean and symmetrical.
Can we make it look similar too for phones/tablets etc.

**Comment by therealmyth** [comment]
Hi Viv, 

This has been added to the home page now, on the left hand side of the page. I also made it mobile/tablet friendly. Let me know if anything.

Fred

**Comment by Vivharris** [comment]
Hi Fred
I can’t see the online valuation tool.
It doesn’t seem to show on my home page.
Best
Viv

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D2FAF2.76A65E90]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Hi Viv, 

You may have to clear your browser's cache, as I had to add some styling to the css which are require for it to work. 

Fred

**Comment by Vivharris** [comment]
Hi Fred
Is the live feed running yet as we are finding that it is not working?
Please can you investigate. We loaded Sheldon Avenue this morning and reloaded Fitzjohns Avenue at £685 per week just now but we can’t see them on the live link.
Please let me know when you can.
Thanks
Viv
T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D2FBF1.36991D60]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32
