### ISSUE TITLE
Add furnished/unfurnished selector

### ISSUE THREAD

**Issue by therealmyth** [ActivateMedia/heathgate#35]
Add a furnished/unfurnished selector in the back-end that will be exported to the portals.

**Comment by therealmyth** [comment]
Hi Viv, 

I've added a new option in Misc Settings (with the export option) to set the property furnished state. This option only affect the live feed. I suggest you go through your rental and set the option to show Zoopla we can support the option. 

Please let me know if anything

Fred

**Comment by therealmyth** [comment]
Hi Viv, 

Not sure if you got this, can you confirm when you have a sec that you can set the furnishing state for your rental on the site? 

Let me know if there's any issue. 

F

**Comment by Vivharris** [comment]
If you are asking whether I now have a pull down menu then yes.
Best
Viv

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D30784.1C3E7890]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Ok, 

Tirrsh seems to say it will help the search for your rental properties, so it's recommended to set this option for every rentals. 

Fred
