### ISSUE TITLE
Photos issue on realtime export. 

### ISSUE THREAD

**Issue by therealmyth** [ActivateMedia/heathgate#36]
Reference: 

Further to the email below I have discovered that the 2 pictures mentioned that appear in Muswell Hill advert are for the property at St John’s Wood Park NW8 at £1,350 per week. Links below.
 
https://www.zoopla.co.uk/to-rent/details/44759537#Ft62K86q4LmBSHbU.97 (Zoopla)
 
http://www.heathgate.com/wp-admin/post.php?post=21503&action=edit (Activate Media)
 
Thanks

> We are having problems with photos on the websites. For some reason they change when they go to Zoopla etc. without our input.
> Please can you address this asap.
>  
> This is the property as it appears on Zoopla.
>  
> https://www.zoopla.co.uk/to-rent/details/44730280#IOJgip466aFoYKTE.97
>  
> This is our activate media link.
>  
> http://www.heathgate.com/wp-admin/post.php?post=21189&action=edit
>  
> As you will see there are 2 pictures appearing on Zoopla which I did not load onto activate media. The 2 pictures are.
>  
> The bathroom with the flowers
> The living room with the furniture.
>  
> Thanks
>

**Comment by therealmyth** [comment]
I've checked the data sent to Zoopla and the correct data is sent. I have submitted the issue to Zoopla and will update when I get any update. Below is the email I sent: 

Fred

Hi Tirrish, 

I hope you are well. 

We seems to have some problems with some of the pictures being assigned to properties. For example, if you look at : https://www.zoopla.co.uk/to-rent/details/44759537#Ft62K86q4LmBSHbU.97, the second to last picture shouldn't be the one that is there right now. You can see the source picture at http://www.heathgate.com/property/st-johns-wood-park-st-johns-wood-nw8-2/.

I have checked the json we send, and the correct content is sent (see below).  This is not the first time it has happened, but sometime it seems to fix itself after a few save and re-submit... 

Could you please advise.

{  
   "administration_fees":"Credit referencing checks per person : \u00a330\nGuarantor credit reference checks per person : \u00a330\nAdministration and preparation charges for the tenancy agreement : \u00a3240\n\nInventory check in (if required) at the commencement of the tenancy:\nA charge between \u00a390 and \u00a3990 dependent on the size and contents of the property. Each property varies so an estimate of cost will be provided in the tenancy agreement\n\nInventory check at end of tenancy (payable at the end of the tenancy) :\nA charge between \u00a390 and \u00a3990 dependent on the size and contents of the property. Each property varies so an estimate of cost will be provided in the tenancy agreement.\n\nAdministration and preparation charges for a  tenancy extension or renewal of the tenancy (this charge is payable on renewal or extension of a tenancy) : \u00a3120 for each renewal.\n\nTenancy Deposit Scheme \u2013 Deposit Protection Fee : Currently \u00a357.50 per annum but subject to change.",
   "areas":{  
      "internal":{  
         "minimum":{  
            "value":1118,
            "units":"sq_feet"
         }
      }
   },
   "bathrooms":3,
   "branch_reference":"3785",
   "category":"residential",
   "content":[  
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/reception5.jpg",
         "type":"image",
         "caption":"reception-381"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/bathroom4.jpg",
         "type":"image",
         "caption":"bathroom-470"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/bedroom-26.jpg",
         "type":"image",
         "caption":"bedroom-2-333"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/bedroom-31.jpg",
         "type":"image",
         "caption":"bedroom-3-135"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/bedroom1.jpg",
         "type":"image",
         "caption":"bedroom-259"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/dining1.jpg",
         "type":"image",
         "caption":"dining-34"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/kitchen5.jpg",
         "type":"image",
         "caption":"kitchen-646"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/reception-diner1.jpg",
         "type":"image",
         "caption":"reception-diner-8"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/EPC17.jpg",
         "type":"epc_graph"
      },
      {  
         "url":"http:\/\/www.heathgate.com\/wp-content\/uploads\/2017\/08\/FLOORPLAN-WM1.jpg",
         "type":"floor_plan"
      }
   ],
   "detailed_description":[  
      {  
         "text":"A stylish and beautifully presented three bedroom, penthouse apartment (1,118 sq ft) situated on the 9th floor in this well maintained purpose built block. The property has been recently refurbished throughout with wooden floors, further benefits include communal hot water and heating, which is included in the rent, air conditioning, lift access and 24 hour porter. Boydell Court is located within close proximity to the local amenities and underground stations of both Swiss Cottage and St Johns Wood (Jubilee Line). The monthly rent is equal to GBP5850.00\r\n\r\n&amp;nbsp;\r\n\r\nTenants administration fees are charged at GBP240 per property. Tenants\/guarantors referencing fees are charged at GBP33 per applicant. Inventory check in fees (if required), are dependent on property size and contents and range from GBP150 to GBP850. Inventory check-out fees are dependent on property size and range from GBP150 to GBP850 depending on the size and contents of the property. All prices are inclusive of VAT.\r\n\r\n&amp;nbsp;"
      }
   ],
   "display_address":"St John's Wood Park St John's Wood NW8",
   "furnished_state":"furnished_or_unfurnished",
   "life_cycle_status":"available",
   "listing_reference":"3785_21503",
   "location":{  
      "property_number_or_name":"4",
      "street_name":"Saint John's Wood Park",
      "town_or_city":"London",
      "postal_code":"NW8 6QS",
      "country_code":"GB",
      "coordinates":{  
         "latitude":51.5400175,
         "longitude":-0.1739379
      }
   },
   "pricing":{  
      "transaction_type":"rent",
      "currency_code":"GBP",
      "price":1350,
      "rent_frequency":"per_week"
   },
   "property_type":"flat",
   "total_bedrooms":3
}

**Comment by therealmyth** [comment]
Update: 

Hi Tirrish, 

Sorry for that, that's the link from the admin, here are the links on the front end : 

1: http://www.heathgate.com/property/havanna-drive-temple-fortune-nw11-2/
https://www.zoopla.co.uk/to-rent/details/44730298#6Zq97EQMw2aGZsBb.97
2: http://www.heathgate.com/property/hampstead-way-hampstead-garden-suburb-nw11-2/
https://www.zoopla.co.uk/to-rent/details/44737242#T4ivYZekPyBGsQet.97 (as it appears on Zoopla)

The ids on your side should be: 3785_20821 and 3785_21290 respectively

Regards, 

Fred

------ Original Message ------
From: "Tirrish Caleechurn" <realtimefeeds@zoopla.co.uk>
To: "frederic.turmel@gmail.com" <frederic.turmel@gmail.com>
Sent: 2017-08-29 12:03:34 PM
Subject: RE: Re[2]: Images problems [ ref:_00Db0eX38._500b0181rSN:ref ]


Hello Fred,

Sorry for the late reply but I cannot access your Heathgate link, so I am unable to compare the differences.

Are you able to provide login details or alternatively send me a file with the images in the correct order?

Kind regards,

Tirrish

--------------- Original Message ---------------
From: [frederic.turmel@gmail.com]
Sent: 23/08/2017 16:39
To: realtimefeeds@zoopla.co.uk
Subject: Re[2]: Images problems [ ]

Hi Tirrish,Â 

This seems to be quite spread out, ie:Â 

http://www.heathgate.com/wp-admin/post.php?post=20821&action=edit (as pictures should be)
https://www.zoopla.co.uk/to-rent/details/44730298#6Zq97EQMw2aGZsBb.97 (what is shown on Zoopla)

http://www.heathgate.com/wp-admin/post.php?post=21290&action=edit (photos that should appear)
https://www.zoopla.co.uk/to-rent/details/44737242#T4ivYZekPyBGsQet.97 (as it appears on Zoopla)

Could you escalate the issue as discussed please?

ThanksÂ 

Fred

**Comment by Vivharris** [comment]
Hi Fred and hope you are well.

Unfortunately the issue with the photos has not been resolved. I have checked again and as far as I can see the following properties gave been affected.

Rochester Road
Eldon Grove
Muswell Hill Road

This really needs to get resolved URGENTLY PLEASE !!!

**Comment by therealmyth** [comment]
Hi Viv, 

Unfortunately, they are extremely slow to respond, even if I made it clear this was an emergency. I've re-submitted a request to him, and hopefully will get an answer soon. I also notice that the delete function doesn't seems to be working on the live endpoint, while it was working on the test instance, so I raised the issue as well. 

Copy of email sent: 

```
Hi Tirrish, 

These links worked fine for me, here's another one: 

http://www.heathgate.com/property/rochester-road-camden-nw1/

And

https://www.zoopla.co.uk/to-rent/details/44748749

Notice the 2nd picture, it is not supposed to be attached to that property.

I tried deleting and re-submitting, but it seems that what was working on the test endpoint
doesn't on the live one, the delete call returns the following: 

{
   "listing_reference" : "3785_21418",
   "status" : "UNKNOWN"
}

There's no error returned

while the listing/update returns OK: 

{
   "listing_etag" : "19cff267205d0f1e68378d91a17b1f2c",
   "listing_reference" : "3785_21418",
   "new_listing" : false,
   "status" : "OK",
   "url" : "http://www.zoopla.co.uk/realtime-listings/adf7a2bedfa1635277520bf4468a69f5447381373d58297465399c883332b7f6eb68b"
}

Fred
```

**Comment by Vivharris** [comment]
I will phone Zoopla tomorrow. Thanks


Vivienne Harris

Office: 020 7435 3344
Mobile: 07976 737 172

HEATHGATE
105 Heath Street, Hampstead, London, NW3 6SS
Fax: 020 7433 3344   Website: www.heathgate.com<http://www.heathgate.com>

On 31 Aug 2017, at 18:21, therealmyth <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Viv,

Unfortunately, they are extremely slow to respond, even if I made it clear this was an emergency. I've re-submitted a request to him, and hopefully will get an answer soon. I also notice that the delete function doesn't seems to be working on the live endpoint, while it was working on the test instance, so I raised the issue as well.

Copy of email sent:

Hi Tirrish,

These links worked fine for me, here's another one:

http://www.heathgate.com/property/rochester-road-camden-nw1/

And

https://www.zoopla.co.uk/to-rent/details/44748749

Notice the 2nd picture, it is not supposed to be attached to that property.

I tried deleting and re-submitting, but it seems that what was working on the test endpoint
doesn't on the live one, the delete call returns the following:

{
   "listing_reference" : "3785_21418",
   "status" : "UNKNOWN"
}

There's no error returned

while the listing/update returns OK:

{
   "listing_etag" : "19cff267205d0f1e68378d91a17b1f2c",
   "listing_reference" : "3785_21418",
   "new_listing" : false,
   "status" : "OK",
   "url" : "http://www.zoopla.co.uk/realtime-listings/adf7a2bedfa1635277520bf4468a69f5447381373d58297465399c883332b7f6eb68b"
}

Fred

**Comment by therealmyth** [comment]
From Zoopla this AM: 

Hello Fred,

Good morning, I hope you are well.

I can confirm that I have passed on this information to my catalog team as an escalation and to find a resolution.

Please bare with me during this time.

Kind regards,

Tirrish

**Comment by therealmyth** [comment]
That phone call seems to have them moving... 

```
Hi Tirrish, 

The problem is not the order, the problem is that this pic: https://lc.zoocdn.com/4e22747b811f917354b545ae986f84eabd9c6f99.jpg should not be there.

Not sure what is the issue with you not being able to see the pictures, I can see them all properly, but here's a list of the we send: 

http://www.heathgate.com/wp-content/uploads/2017/08/Kitchen7.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Bathroom4.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Bedroom-with-en-suite.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Bedroom7.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Reception5.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Shower-room.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Terrace-2.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Terrace.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Floorplan4.jpg
http://www.heathgate.com/wp-content/uploads/2017/08/Exterior7.jpg

I attach to this email the json that is sent to your endpoint for the property in question, keep in mind that this happened to more than one property, but let's focus on fixing that one and hopefully this will fix it for all of them.

Did you also mention about the deletion issue?

Let me know

Fred

------ Original Message ------
From: "Tirrish Caleechurn" <realtimefeeds@zoopla.co.uk>
To: "frederic.turmel@gmail.com" <frederic.turmel@gmail.com>
Sent: 2017-09-01 11:49:29 AM
Subject: RE: Re[6]: Images problems [ ref:_00Db0eX38._500b0181rSN:ref ]

Hello Fred,

Please see below for a response from our catalog team: 

Please submit more details of the conflict. all I can see here is that the 2nd photo on zpg is currently
https://lc.zoocdn.com/2fe6a2c6038a08fb6192cac4554b3e51652f64b2.jpg
when it should possible be
https://lc.zoocdn.com/4e22747b811f917354b545ae986f84eabd9c6f99.jpg
but the order is different on the users homepage link anyway. so to clarify:
is it the order of the photos that is the issue? if so what order (this cannot actually be remedied easily)
is there an incorrect photo on site? if so which one?
We are both struggling to see the images you provided in the link.

If you could attach a file of images we are suppose to see this would help.

I await your response.

Kind regards,

Tirrish 
```

**Comment by Vivharris** [comment]
Thanks Fred
Ok. Also on sales Fitzjohns Avenue £1.2m. Floorplans all wrong.
Let me know if they are dragging their heels and I will send a rocket over.
Have a good weekend.
Viv

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D32353.AC14D320]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by Vivharris** [comment]
I uploaded Frognal @ £995 per week on Friday. Not showing at all on Zoopla.
Please assist urgently.
Thanks
Vivienne

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D32562.89583B40]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by Vivharris** [comment]
It's now got worse as some my  of my properties are not showing at all. I spoke to Will there this morning and he has spoken to Tirrish. I have said that this needs to be sorted out today. Will says he will be in touch and please, please stay on top of them. I cant have a site where my properties aren't showing. Fitzjohns Avenue NW3 asking £1.2m is now not showing having shown be it incorrectly on Friday.
Please let me know what you need me to do to keep the pressure up. I have given them a huge kick today. Thanks
