### ISSUE TITLE
A slight change to our site please 

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#37]
Hi Fred and Greg
Please can we make a further amendment to the site so that I can just upload some properties to all sites and some to either others or none.
Is there a way that we can have an export menu that says Zoopla, Onthemarket and Rightmove that we can tick so that it uploads to each one individually? Unticked can remain as just the Heathgate site.
Thanks
Viv

**Comment by Vivharris** [comment]
Hi Fred and Greg
Please can we make a further amendment to the site so that I can just upload some properties to all sites and some to either others or none.
Is there a way that we can have an export menu that says Zoopla, Onthemarket and Rightmove that we can tick so that it uploads to each one individually? Unticked can remain as just the Heathgate site.
Thanks
Viv

**Comment by therealmyth** [comment]
Hi Viv, 

The change requested above has been done. You will now see one checkbox for each portal under Misc. Settings, letting you choose individual portals you want to property to be exported to:

Export to Zoopla   
Export to homesandproperty.co.uk   
Export to Prime Location   
Export to Rightmove   
Export to Net Houses Prices   
Export to Agents Mutual   

They are all selected at the moment for the properties that were set to be exported to reflect the state before the change.

Let me know if anything

Fred

**Comment by Vivharris** [comment]
Hi Fred
Thanks for this.
Have you checked the links? Especially to Agents Mutual?
Zoopla and Primelocation are in fact the same so we won’t need both.
I had an email from Nethouseprices.com today that says I am not on the site anymore so I think the link is broken to that site? Is there a way you can check?
Thanks
Viv
T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D336D0.695A9D40]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32

**Comment by therealmyth** [comment]
Hi Viv

I didn't check the links no, I just enabled the ones that were active in the system already. I will disable Prime Location, since it's the same as Zoopla. 

I ran the script manually today to make sure there was no errors, and all uploads worked as expected, but I have no way to know what happened on their side with the upload.  I can see that 91 properties were exported to Nethouseprices.com during the test this am, not sure why they are not showing up on their side, could you try and get some info from them about that? or get me in touch with your contact there and I will. 

Fred

**Comment by Vivharris** [comment]
Have left him a message – will be in touch.
Thanks Fred.
V

T      020 7435 3344
DDI  020 7096 9341
M     07976 737 172
E      viv@heathgate.co.uk<mailto:vivharris@heathgate.co.uk>
[cid:image011.png@01D20450.6B3DE940]

home<http://www.heathgate.com/> | sales<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2> | lettings<http://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3> | management<http://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4> | hampstead<http://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7> | contact us<http://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10>

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.uk<mailto:property@heathgate.co.uk>    Website: www.heathgate.com<http://www.heathgate.com/>

                [cid:image005.png@01D336F2.74EF9440]
        [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>




FOLLOW:                               LIKE:                              SEE:


© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32
