### ISSUE TITLE
Property details in Zoopla not matching CMS

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/heathgate#4]
The details of this property on Zoopla -

http://www.zoopla.co.uk/for-sale/details/41318409?search_identifier=fcea19771ae0ebc6043e01e6d99ca57f#mF0Vxu8s0LkZFFOA.97

do not match what is in the CMS -

http://www.heathgate.com/wp-admin/post.php?post=12385&action=edit

The property title does not match and the Zoopla listing is showing photos from a different property -

http://www.heathgate.com/wp-admin/post.php?post=7647&action=edit

**Comment by adrian-activate** [comment]
@therealmyth there seems to be an issue with just this property as it is also causing an issue on -

https://www.onthemarket.com/details/3036168/

Here the images are missing.

**Comment by therealmyth** [comment]
@adrian-activate 

There was 2 issues with the script: 

1 - Title: The title on zoopla is based on the address we pass to them. The address is derived from the address object returned by Google, which for thsi property was: 

> "address_components" : [
>             {
>                "long_name" : "Saint Regis Heights",
>                "short_name" : "St Regis Heights",
>                "types" : [ "premise" ]
>             },
>             {
>                "long_name" : "Firecrest Drive",
>                "short_name" : "Firecrest Dr",
>                "types" : [ "route" ]
>             },

I added support for the premise and the title should reflect more what on the website. 

2 - images: The script was getting the image list the wrong way. it was looking for posts with parent = property id and type - attachment. This was sometimes returning a link to an attachment (ie http://www.heathgate.com/?attachment_id=x). I cerrected the query to fetch the posts based on the post meta values.

I'm running the script manually right now. will have a look later to see if it has fixed the issue.

**Comment by adrian-activate** [comment]
@therealmyth all seems ok but the EPC and the floorplan seem to be missing now.

**Comment by adrian-activate** [comment]
@therealmyth any news on this please?

**Comment by fredturmel** [comment]
sorry Adrian I must have missed the notification for your update. I will have a look at it today

**Comment by fredturmel** [comment]
@adrian-activate : I'm running the script right now, I think I found the issue, will confirm in a few hours when the portals are updated with the latest export.

**Comment by fredturmel** [comment]
@adrian-activate : The floorplans and EPC reports are on the portals now.

**Comment by adrian-activate** [comment]
Thanks Fred
