### ISSUE TITLE
Empty zip files being sent to Zoopla

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/heathgate#5]
Hi Doug, 
 
Just a quick update on the feed issue as well. 
 
Having investigated this and checking the logs I have found that a .blm file has been uploaded to our servers by Activate media but those zip files are all empty. These are the ones that was uploaded yesterday.
 
37852016102803.zip|grep BLM
0 10-28-2016 12:14 37852016102803.BLM
 
I hope this helps, If you need any further information please let me know.
 
Thanks 
 
Kind Regards, 
 
Dona Jose
Technical Support Executive, ZPG

**Comment by Vivharris** [comment]
Any news re our issues today? We are unable to operate without the website working properly, Please can you attend to these issues asap. Thanks Viv

**Comment by therealmyth** [comment]
There was 2 issues with the feed: 

1)  Google changed their API and are now limiting the number of anonymous request to the GeoCode API, which we uses to get proper address objects derived from the property names. I had to register an app with them and it fixed that issue. The free API is still limited to 2500 calls per day per app, so I had to modify the script a little to reduce the number of calls to get below that limit. 

2)  The feed data encoding needs to be converted to UTF-8 and there was a character in the Boydell Court listing that was triggering an error in the function we used to do the conversion. I have changed to another function, and it seems to be more error tolerant. The feed is no longer empty

**Comment by Vivharris** [comment]
Thank you
V

T   020 7435 3344
M 07976 737172
E   vivharris@heathgate.co.ukmailto:vivharris@heathgate.co.uk
[cid:image011.png@01D20450.6B3DE940]

homehttp://www.heathgate.com/ | saleshttp://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=1&beds=0&baths=0&price_low=0&price_high=0&Itemid=2 | lettingshttp://www.heathgate.com/index.php?option=com_iproperty&view=list&id=0&stype=2&beds=0&baths=0&price_low=0&price_high=0&Itemid=3 | managementhttp://www.heathgate.com/index.php?option=com_content&view=article&id=3&Itemid=4 | hampsteadhttp://www.heathgate.com/index.php?option=com_content&view=article&id=6&Itemid=7 | contact ushttp://www.heathgate.com/index.php?option=com_content&view=article&id=1&Itemid=10

105 Heath Street, Hampstead, London. NW3 6SS
Tel: +44 (020) 7435 3344    Fax: +44 (020) 7433 3344    Email: property@heathgate.co.ukmailto:property@heathgate.co.uk    Website: www.heathgate.comhttp://www.heathgate.com/

```
            [cid:image008.png@01D23422.6BF868E0]
    [Follow us on Twitter] <https://twitter.com/heathgateuk>                [Find us on Facebbok] <https://www.facebook.com/pages/Heathgate-Estate-Agents/118792764814982>
```

FOLLOW:                               LIKE:                              SEE:

© Copyright 2013 The Heathgate Group Limited. All rights reserved. Disclaimer: The information contained in this email is confidential and may be subject to legal privilege. Access to this email by anyone other than the intended recipient is unauthorised. If you are not the intended recipient, you must not use, copy, distribute or disclose this email or any part of its contents or take any action in reliance on it. If you have received this email in error, please notify us immediately by email or telephone +44 (0) 20 7435 3344. All reasonable precautions have been taken to ensure no viruses are present in this email. Heathgate is the trading name of The Heathgate Group Limited and is registered in England at 28 Church Road, Stanmore, Middlesex, HA7 4XR. Registered number 2535191. VAT No.: 544 6804 32
