### ISSUE TITLE
Switching to Zoopla real time data feed

### ISSUE THREAD

**Issue by adrian-activate** [ActivateMedia/heathgate#6]
@therealmyth can we get an idea of what we would need to do from our side to implement this?

```
Hi Doug, 
 
Nice speaking to you earlier ! 
 
As discussed, please find below the Zoopla Realtime Data feed and the specification can be found here:
 
https://realtime-listings.webservices.zpg.co.uk/docs/latest/documentation.html
 
Please be aware that with the Real Time data feed we require 7 days of error free data before the feed gets approved. If you make an error, that counter will be reset so please be aware this can take slightly longer.
 
If you wish to proceed with this please see section 3 and follow the steps in order to request a certificate.
 
If you have any further questions or if I can be of further assistance please do not hesitate to contact me.
 
Kind Regards, 
 
Dona Jose
Technical Support Executive, ZPG
```

**Comment by adrian-activate** [comment]
@therealmyth Could we integrate https://wp-property-hive.com/ into what we have? It has plugins that support both blm exports and real-time datafeed. We could then replace the custom script. Just not sure if this would work with wp-casa.

**Comment by therealmyth** [comment]
I will look into this at the same time then the empty zip files.

**Comment by therealmyth** [comment]
I have checked the link below, the plugin for the feed at £199 or the Portal BLM export at £149 is designed for Property Hive, which is the equivalent to WPCasa. It is not compatible with it to my knowlege and to use it, we would need to migrate the data from WPCasa to Property Hive.
