### ISSUE TITLE
Postcodes

### ISSUE THREAD

**Issue by Vivharris** [ActivateMedia/heathgate#9]
Sometimes when we put in a postcode when loading a property (say NW3 6SS) we find that it changes to just NW3 and then won't load onto the other portals. Can you please investigate this for us. Thanks V

**Comment by therealmyth** [comment]
Hi Viv, 

I will investigate the issue and come back to you. Excuse the delay in my response, I wasn't set to receive notification on this channel, which I changed for now on. 

Regards, 

f

**Comment by therealmyth** [comment]
Could not replicate the issue locally, if you notice the issue again, please let me know the exact property having the problem along with the correct postcode that should appear so I can test. It maybe caused by the google API, to which we pass the address to extract it's components.
